# -*- coding: utf-8 -*-
"""Data_Bootcamp_Final_Movies .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fu3SkDl_RSv-_UclaU95lPprCd9q-0E-

#Research Question: "To what extent can YouTube marketing metrics and film metadata be integrated to predict the commercial success of a movie?"

In this section, we install the necessary libraries and configure the API environment to fetch high-fidelity data from TMDB and YouTube.
"""

#pip install isodate 

# Dataset building and EDA libraries
import requests
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import datetime as dt
import isodate as iso
# Preprocessing and pipeline libraries
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
# Modeling libraries
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score, classification_report, confusion_matrix
from sklearn.ensemble import RandomForestClassifier,  RandomForestRegressor
from sklearn.cluster import KMeans
from sklearn.model_selection import GridSearchCV, train_test_split, cross_val_score

#API variables
TMDB_API_KEY =  "75eae8eb183176f7699436684cd8e790"
YOUTUBE_API_KEY = "AIzaSyBlfqmdnH7AKG8yBai8iRiPEuaZSxgGGZw"

TMDB_BASE = "https://api.themoviedb.org/3"
YOUTUBE_BASE = "https://www.googleapis.com/youtube/v3/videos"

endpoints = ["upcoming", "now_playing", "popular", "top_rated"]

"""### Data Description & Feature Engineering"""

# fetches all the movie data from the different endpoints and places them into an array
def fetch_movies(pages = 4):
  all_movies = []
  unique = set()
  for endpoint in endpoints:
    for page in range(1, pages + 1):
      response = requests.get(f"{TMDB_BASE}/movie/{endpoint}", params= {"api_key": TMDB_API_KEY, "page": page})
      movies = response.json().get("results", [])
      # removes duplicates of movies in list
      for movie in movies:
        movie_id = movie["id"]
        if (movie_id in unique):
          continue
        unique.add(movie_id)
        movie["category"] = endpoint
        all_movies.append(movie)
  return all_movies

len(fetch_movies())

# regulates data to place into a pandas Dataframe for the EDA
def create_movie_dataset(movies):
    dataset = []

    for movie in movies:
        try:
            movie_id = movie["id"]

            result = requests.get(
                f"{TMDB_BASE}/movie/{movie_id}",
                params={
                    "api_key": TMDB_API_KEY,
                    "append_to_response": "credits"
                }
            ).json()

            # genres
            genres = [g["name"] for g in result.get("genres", [])]

            # director
            director = next(
                (d["name"] for d in result.get("credits", {}).get("crew", [])
                 if d.get("job") == "Director"),
                None
            )

            # top 3 actors
            actors = [
                c.get("name")
                for c in result.get("credits", {}).get("cast", [])[:3]
            ]

            # trailer info (TMDB)
            vid_results = requests.get(
                f"{TMDB_BASE}/movie/{movie_id}/videos",
                params={"api_key": TMDB_API_KEY}
            ).json()

            trailer_key = None
            for v in vid_results.get("results", []):
                if v.get("site") == "YouTube" and v.get("type") == "Trailer":
                    trailer_key = v.get("key")
                    break

            if not trailer_key:
                continue

            # YouTube stats
            yt_results = requests.get(
                YOUTUBE_BASE,
                params={
                    "part": "statistics,snippet,contentDetails",
                    "id": trailer_key,
                    "key": YOUTUBE_API_KEY
                }
            ).json()

            items = yt_results.get("items", [])
            if not items:
                continue

            video = items[0]
            stats = video.get("statistics", {})
            snippet = video.get("snippet", {})
            content = video.get("contentDetails", {})

            dataset.append({
                "movie_id": movie_id, "title": movie.get("title"), "category": movie.get("category"),
                "genres": genres, "director": director,"top_actors": actors,
                "original_language": movie.get("original_language"), "release_date": movie.get("release_date"),
                "popularity": movie.get("popularity"), "vote_average": movie.get("vote_average"), "vote_count": movie.get("vote_count"),
                "youtube_video_id": trailer_key, "youtube_title": snippet.get("title"), "youtube_published": snippet.get("publishedAt"),
                "trailer_views": int(stats.get("viewCount", 0)), "trailer_likes": int(stats.get("likeCount", 0)),
                "trailer_comments": int(stats.get("commentCount", 0)), "trailer_duration": content.get("duration"),
            })

        except Exception as e:
            print(f"Error on {movie.get('title', 'unknown')}: {e}")

    return pd.DataFrame(dataset)

movie_list = fetch_movies()
eda_df = create_movie_dataset(movie_list)

eda_df.head()

# fixing and creating date time columns
# ---- datetime conversion ----
eda_df["release_date"] = pd.to_datetime(eda_df["release_date"], errors="coerce")
eda_df["youtube_published"] = pd.to_datetime(eda_df["youtube_published"], errors="coerce")
# release features
eda_df["release_year"] = eda_df["release_date"].dt.year
eda_df["release_month"] = eda_df["release_date"].dt.month
eda_df["release_day"] = eda_df["release_date"].dt.day
# youtube publish features
eda_df["publish_year"] = eda_df["youtube_published"].dt.year
eda_df["publish_month"] = eda_df["youtube_published"].dt.month
eda_df["publish_day"] = eda_df["youtube_published"].dt.day
# duration conversion
eda_df["trailer_duration"] = eda_df["trailer_duration"].apply(lambda x: iso.parse_duration(x).total_seconds() if pd.notnull(x) else None)

eda_df.tail()

# Explode genres to analyze individually
eda_df_genres = eda_df.explode('genres')

# Calculate engagement ratio
eda_df['engagement_ratio'] = eda_df['trailer_likes'] / eda_df['trailer_views']

"""#EDA ANALYSIS"""

# correlation heatmap for popularity
correlation_cols = ['popularity', 'vote_average', 'trailer_views', 'trailer_likes', 'trailer_comments',"engagement_ratio"]
corr_matrix = eda_df[correlation_cols].corr()
print("Correlation between TMDB Popularity and YouTube Views:", corr_matrix.loc['popularity', 'trailer_views'])
sns.heatmap(corr_matrix,annot=True,cmap="viridis")

# trailer views vs popularity
plt.figure(figsize=(10, 6))
sns.scatterplot(data=eda_df, x='popularity', y='trailer_views', size='vote_average', hue='vote_average', palette='viridis')
plt.title('TMDB Popularity vs. YouTube Trailer Views')
plt.xlabel('TMDB Popularity Score')
plt.ylabel('YouTube Trailer Views')
plt.show()

#genre trends over time
# Average trailer views by genre
genre_performance = eda_df_genres.groupby('genres')['trailer_views'].mean().sort_values(ascending=False)
print(genre_performance)
genre_trends = (eda_df_genres.groupby(["release_year", "genres"])["popularity"].mean().reset_index())
pivot = genre_trends.pivot(index="genres",columns="release_year", values="popularity")
plt.figure(figsize=(18,8))
sns.heatmap(pivot,cmap="viridis",linewidths=0.3)
plt.title("Genre Popularity by Year")
plt.xlabel("Release Year")
plt.ylabel("Genre")
plt.show()

#success based on original language
lang_success = (eda_df.groupby("original_language")[["popularity","vote_average","trailer_views"]].mean().sort_values(by="popularity", ascending=False))
print(lang_success.head(10))

#popularity based on month/season
month_popularity = (eda_df.groupby("release_month")["popularity"].mean())
plt.figure(figsize=(10,6))
month_popularity.plot(kind="bar")
plt.title("TMDB Average Popularity by Release Month")
plt.ylabel("TMDB Popularity")
plt.show()

# population vs ratings
plt.figure(figsize=(10,6))
sns.scatterplot( data=eda_df,x="vote_average",y="popularity",)
plt.title("TMDB Popularity vs Ratings")
plt.show()

#trailer duration vs popularity
plt.figure(figsize=(10,6))
sns.scatterplot(data=eda_df,x="trailer_duration",y="popularity")
plt.title("YT Trailer Duration vs TMDB Movie Popularity")
plt.xlabel("Trailer Duration (seconds)")
plt.xlim(None, 200)
plt.ylabel("Popularity")
plt.show()

# # Top 5 movies by engagement ratio, grouped by endpoint
# top_per_category = (eda_df.groupby("category").apply(lambda x: x.nlargest(5, "engagement_ratio")).reset_index(drop=True))
# top_per_category[["category","title","trailer_views", "trailer_likes","engagement_ratio"]]

# print(top_per_category)
# top_engagement = eda_df.nlargest(5, 'engagement_ratio')[['title', 'trailer_views', 'trailer_likes', 'engagement_ratio']]
# print(top_engagement)

"""#MODELING"""

# Prepare data
X = eda_df[['popularity']] # Feature
y = eda_df['trailer_views'] # Target

# Week 10: Train/Test Split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialize and train model
model = LinearRegression()
model.fit(X_train, y_train)

# Predict and Evaluate
y_pred = model.predict(X_test)
print(f"R-squared Score: {r2_score(y_test, y_pred):.4f}")
print(f"Coefficient (Weight): {model.coef_[0]:.2f}")

# Create target: 1 if vote_average > 7.0, else 0
eda_df['is_hit'] = (eda_df['vote_average'] > 7.0).astype(int)

# Features: Popularity, Views, Likes, Comments
features = ['popularity', 'trailer_views', 'trailer_likes', 'trailer_comments']
X = eda_df[features]
y = eda_df['is_hit']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Using Random Forest (Classification)
clf = RandomForestClassifier(n_estimators=100)
clf.fit(X_train, y_train)

# Evaluation
y_pred = clf.predict(X_test)
print(classification_report(y_test, y_pred))

# Select engagement features
cluster_data = eda_df[['trailer_views', 'trailer_likes', 'trailer_comments']]

# Week 10/12: Scaling data is crucial for Clustering
scaler = StandardScaler()
scaled_data = scaler.fit_transform(cluster_data)

# Apply KMeans
kmeans = KMeans(n_clusters=3, random_state=42)
eda_df['cluster_group'] = kmeans.fit_predict(scaled_data)

# View the groups
print(eda_df[['title', 'cluster_group']].sort_values(by='cluster_group'))

# Check stability of the Linear Regression model
cv_scores = cross_val_score(model, X, y, cv=5) # 5-fold cross validation

print(f"All CV Scores: {cv_scores}")
print(f"Mean CV R-squared: {np.mean(cv_scores):.4f}")

# 1. Prepare Features and Target
# Using numerical and categorical columns
features = ['popularity', 'vote_count', 'original_language']
X = eda_df[features]
y = eda_df['trailer_views']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# 2. Define Transformers (Week 10: Transformers)
numeric_features = ['popularity', 'vote_count']
numeric_transformer = Pipeline(steps=[
    ('scaler', StandardScaler())
])

categorical_features = ['original_language']
categorical_transformer = Pipeline(steps=[
    ('onehot', OneHotEncoder(handle_unknown='ignore'))
])

# 3. Combine into a ColumnTransformer
preprocessor = ColumnTransformer(
    transformers=[
        ('num', numeric_transformer, numeric_features),
        ('cat', categorical_transformer, categorical_features)
    ])

# 4. Create the Full Pipeline
pipeline = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('regressor', RandomForestRegressor(random_state=42))
])

# 5. Grid Search & Cross-Validation (Week 10: Grid Searching)
param_grid = {
    'regressor__n_estimators': [50, 100, 200],
    'regressor__max_depth': [None, 10, 20],
    'regressor__min_samples_split': [2, 5]
}

grid_search = GridSearchCV(pipeline, param_grid, cv=5, scoring='r2', n_jobs=-1)

# 6. Fit the Model
grid_search.fit(X_train, y_train)

# 7. Results
print(f"Best Parameters: {grid_search.best_params_}")
print(f"Best Cross-Validation Score (R2): {grid_search.best_score_:.4f}")

# Evaluate on Test Set
test_score = grid_search.score(X_test, y_test)
print(f"Test Set R2 Score: {test_score:.4f}")

"""#"At the end of this study, we concluded that industry popularity is not a mirror for audience hype. While TMDB might rank a movie highly, the YouTube audience reacts to different triggers. This proves that for a movie to be successful in 2026, marketing teams cannot rely on industry scores alone; they must bridge the gap using deeper engagement analytics."


"""